In [1]:
import tensorflow as tf
# input
temp = tf.constant([0, 1, 0, 1, 2, 1, 1, 0, 3, 1, 1, 0, 4, 4, 5, 4], tf.float32)
temp2 = tf.reshape(temp, [2, 2, 2, 2])
# conv2d
filter = tf.constant([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], tf.float32)
filter2 = tf.reshape(filter, [2, 2, 2, 2])
#
convolution = tf.nn.conv2d(temp2, filter2, [1, 1, 1, 1], padding="SAME")
#
session = tf.Session()
tf.global_variables_initializer()
# 
print("input data: ")
print(session.run(temp2))
print("conv2d data: ")
print(session.run(filter2))
print("conv2d output: ")
print(session.run(convolution))

input data: 
[[[[0. 1.]
   [0. 1.]]

  [[2. 1.]
   [1. 0.]]]


 [[[3. 1.]
   [1. 0.]]

  [[4. 4.]
   [5. 4.]]]]
conv2d data: 
[[[[1. 1.]
   [1. 1.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
conv2d output: 
[[[[1. 1.]
   [1. 1.]]

  [[3. 3.]
   [1. 1.]]]


 [[[4. 4.]
   [1. 1.]]

  [[8. 8.]
   [9. 9.]]]]


In [2]:
convolution = tf.nn.conv2d(temp2, filter2, [1, 1, 1, 1], padding="VALID")

print("conv2d output2: ")
print(session.run(convolution))

conv2d output2: 
[[[[1. 1.]]]


 [[[4. 4.]]]]
