In [10]:
import tensorflow as tf

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    d = tf.constant([
        [1., 2., 3., 4.],
        [5., 6., 7., 8.],
        [9., 10., 11., 12.],
        [13., 14., 15., 16.]
    ])
    print(sess.run(tf.shape(d)))
    print(sess.run(d))
    print("--------------------------------------")
    dropout_d = tf.nn.dropout(d, 0.5)
    result_dropout_d = sess.run(dropout_d)
    print(result_dropout_d)
    print("--------------------------------------")
    dropout_d41 = tf.nn.dropout(d, 0.5, noise_shape = [4, 1])
    result_dropout_d41 = sess.run(dropout_d41)
    print(result_dropout_d41)
    print("--------------------------------------")
    dropout_d14 = tf.nn.dropout(d, 0.5, noise_shape = [1, 4])
    result_dropout_d14 = sess.run(dropout_d14)
    print(result_dropout_d14)

[4 4]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
--------------------------------------
[[ 0.  4.  0.  8.]
 [ 0. 12. 14.  0.]
 [18.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
--------------------------------------
[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [ 0.  0.  0.  0.]
 [26. 28. 30. 32.]]
--------------------------------------
[[ 2.  4.  0.  0.]
 [10. 12.  0.  0.]
 [18. 20.  0.  0.]
 [26. 28.  0.  0.]]
