In [8]:
import tensorflow as tf
import numpy as np
input_data = np.array([i for i in range(0, 32)])
reshape_data = tf.reshape(input_data, [2, 2, 2, 4])
reshape_data2 = tf.to_float(reshape_data)

In [9]:
lrn = tf.nn.local_response_normalization(
input = reshape_data2, depth_radius = 2, bias = 0, alpha = 1, beta = 1)

In [11]:
with tf.Session() as sess:
    print(reshape_data2.eval())
    print('After LRN: ')
    print(lrn.eval())

[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]]

  [[ 8.  9. 10. 11.]
   [12. 13. 14. 15.]]]


 [[[16. 17. 18. 19.]
   [20. 21. 22. 23.]]

  [[24. 25. 26. 27.]
   [28. 29. 30. 31.]]]]
After LRN: 
[[[[0.         0.07142857 0.14285715 0.21428573]
   [0.05194805 0.03968254 0.04761905 0.06363636]]

  [[0.03265306 0.02459016 0.0273224  0.03642384]
   [0.02357564 0.01771117 0.01907357 0.02542373]]]


 [[[0.01841197 0.01382114 0.01463415 0.01950719]
   [0.01509434 0.01132686 0.01186623 0.01581843]]

  [[0.01278636 0.00959325 0.00997698 0.01330049]
   [0.01108911 0.00831899 0.00860585 0.01147298]]]]
