In [2]:
import tensorflow as tf
import numpy as np
A = list([1, 2, 3])
B = np.array([4, 5, 6], dtype = np.int32)
C = tf.convert_to_tensor(A)
D = tf.convert_to_tensor(B)
E = tf.add(C, D)

with tf.Session() as sess:
    print(type(A))
    print(type(B))
    print(type(C))
    print(type(D))
    print(sess.run(E))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
[5 7 9]


In [3]:
a = np.array([1, 2], dtype = np.int32)
b = np.array([3, 4], dtype = np.int32)
c = tf.add(a, b)
sess = tf.Session()
sess.run(c)

array([4, 6], dtype=int32)

In [4]:
d = a + c
sess.run(d)

array([5, 8], dtype=int32)

In [11]:
tf.negative(a)
tf.logical_not(a)
tf.abs(a)

<tf.Tensor 'Abs:0' shape=(2,) dtype=int32>